backend:
  name: git-gateway
  repo: vanjaka-korporacija/kuhinja404
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "recepti"
    label: "Recepti"
    folder: "recepti"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Slika", name: "image", widget: "image"}
      - {label: "Sastojci", name: "sastojci", widget: "markdown"}
      - {label: "Postupak", name: "postupak", widget: "markdown"}
